# Generated by Django 5.2.6 on 2026-09-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id_actualite', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('date_publication', models.DateField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'actualites',
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id_candidat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('photo', models.CharField(max_length=255, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('lieu_naissance', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('adresse_email', models.CharField(max_length=255, null=True)),
                ('droit_concours', models.BooleanField(null=True)),
                ('est_eleve', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'candidats',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('fonction', models.CharField(max_length=255, null=True)),
                ('titre', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'equipe',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id_formation', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'formations',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id_information', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=255, null=True)),
                ('numero_telephone', models.CharField(max_length=255, null=True)),
                ('adresse_email', models.CharField(max_length=255, null=True)),
                ('historique', models.TextField(null=True)),
                ('lieu_code_map', models.CharField(max_length=255, null=True)),
                ('agrement', models.CharField(max_length=255, null=True)),
                ('comment_nous_rejoindre', models.TextField(null=True)),
                ('adresse_local', models.CharField(max_length=255, null=True)),
                ('contacts', models.TextField(null=True)),
            ],
            options={
                'db_table': 'informations',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id_partenaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('logo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'partenaires',
            },
        ),
        migrations.CreateModel(
            name='TypeArchive',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'types_archive',
            },
        ),
        migrations.CreateModel(
            name='TypeDossier',
            fields=[
                ('id_type_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'types_dossier',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('adresse_email', models.CharField(max_length=255, null=True)),
                ('mot_de_passe', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='ConditionAcces',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.TextField(null=True)),
                ('id_formation', models.ForeignKey(db_column='id_formation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='conditions', to='api.formation')),
            ],
            options={
                'db_table': 'conditions_acces',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id_archive', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('id_type', models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.DO_NOTHING, related_name='archives', to='api.typearchive')),
            ],
            options={
                'db_table': 'archives',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255, null=True)),
                ('fin_validite', models.DateField(null=True)),
                ('descriptions', models.TextField(null=True)),
                ('id_candidat', models.ForeignKey(db_column='id_candidat', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dossiers', to='api.candidat')),
                ('id_type_dossier', models.ForeignKey(db_column='id_type_dossier', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dossiers', to='api.typedossier')),
            ],
            options={
                'db_table': 'dossiers',
            },
        ),
    ]
