CREATE TABLE "formations" (
  "id_formation" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "type" varchar,
  "description" text
);

CREATE TABLE "conditions_acces" (
  "numero" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_formation" int,
  "condition" text
);

CREATE TABLE "informations" (
  "id_information" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "logo" varchar,
  "numero_telephone" varchar,
  "adresse_email" varchar,
  "historique" text,
  "lieu_code_map" varchar,
  "agrement" varchar,
  "comment_nous_rejoindre" text,
  "adresse_local" varchar,
  "contacts" text
);

CREATE TABLE "types_archive" (
  "id_type" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar
);

CREATE TABLE "archives" (
  "id_archive" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_type" int,
  "nom" varchar
);

CREATE TABLE "partenaires" (
  "id_partenaire" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "logo" varchar
);

CREATE TABLE "actualites" (
  "id_actualite" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" varchar,
  "description" text,
  "date_publication" date,
  "image" varchar
);

CREATE TABLE "equipe" (
  "id_equipe" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "prenom" varchar,
  "fonction" varchar,
  "titre" varchar,
  "image" varchar
);

CREATE TABLE "candidats" (
  "id_candidat" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "prenom" varchar,
  "photo" varchar,
  "date_naissance" date,
  "lieu_naissance" varchar,
  "contact" varchar,
  "adresse_email" varchar,
  "droit_concours" boolean,
  "est_eleve" boolean
);

CREATE TABLE "types_dossier" (
  "id_type_dossier" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar
);

CREATE TABLE "dossiers" (
  "id_dossier" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_type_dossier" int,
  "id_candidat" int,
  "image" varchar,
  "fin_validite" date,
  "descriptions" text
);

CREATE TABLE "utilisateurs" (
  "id_utilisateur" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "prenom" varchar,
  "adresse_email" varchar,
  "mot_de_passe" varchar
);

ALTER TABLE "conditions_acces" ADD FOREIGN KEY ("id_formation") REFERENCES "formations" ("id_formation") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "archives" ADD FOREIGN KEY ("id_type") REFERENCES "types_archive" ("id_type") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dossiers" ADD FOREIGN KEY ("id_type_dossier") REFERENCES "types_dossier" ("id_type_dossier") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dossiers" ADD FOREIGN KEY ("id_candidat") REFERENCES "candidats" ("id_candidat") DEFERRABLE INITIALLY IMMEDIATE;
